---
version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
artifacts:
  files:
    - '**/*'
    #- Dockerfile
    #- app.js
    #- buildspec.yml
    #- package.json
  #base-directory: consultaloja
  #discard-paths: yes
...
