---

- name: Include environment static vars
  include_vars: ../../../inventories/{{ env }}/{{ env }}.yml

- name: Generate private ssh key
  openssl_privatekey:
    path: "{{ ssh_priv_key }}"
    force: True
    state: present

- name: Generate public ssh key
  openssl_publickey:
    force: True
    format: OpenSSH
    path: "{{ ssh_pub_key }}"
    privatekey_path: "{{ ssh_priv_key }}"
    state: present
  register: public_key

- name: Change private key permissions
  file: 
    path: "{{ ssh_priv_key }}"
    mode: 0600

- name: Assign ssh key to a variable
  shell:
    cat {{ ssh_pub_key }}
  register: public_key

- name: Deploy generated key to gitlab
  gitlab_deploy_key:
    api_url: "{{ gitlab_api }}"
    private_token: "{{ gitlab_token }}"
    project: "{{ gitlab_project_id }}"
    title: "{{ project_name }} key"
    state: present
    key: "{{ public_key.stdout }}"
    can_push: yes

- name: Copy ssh config to local machine
  template: 
    src: ../files/config.j2
    dest: ~/.ssh/config

- name: Checkout files to local machine
  git: 
    repo: "{{ git_repo }}"
    dest: "{{ source_code_path }}"
    version: "{{ git_branch }}"

- name: Delete generated key from gitlab
  gitlab_deploy_key:
    api_url: "{{ gitlab_api }}"
    private_token: "{{ gitlab_token }}"
    project: "{{ gitlab_project_id }}"
    state: absent
    title: "{{ project_name }} key"
    key: "{{ public_key.stdout }}"

# - name: Zip the source code
#   archive: 
#     path: "{{ source_code_path }}/"
#     dest: ~/{{ artifact_name }} 
#     format: zip 

...