tfstate_bucket_name = "aws-demo-tfstate-bucket"
artifact_bucket_name = "claro-artifact-store-aws-demo-bucket"
aws_local_profile = "aws-demo"
aws_region = "us-east-1"
tags = {
  ambiente        = "dev"
  torre           = "digital"
  marca           = "multimarca"
  centro-de-custo = "x"
  projeto         = "aws-demo"
  servico         = "aws-demo"
  conta           = "dev-ongoing"
  plataforma      = "aws"
  produto         = "demo"
}
