## TF_INFRA ROLE VARS
tf_state: present  # present / absent / planned
tf_state_bucket: aws-demo-tfstate-bucket
tf_state_bucket_key: dev.tfstate
tf_variables_file_path:

aws_region: us-east-1
aws_local_profile: aws-demo
aws_tf_lock_dynamodb_table: terraform-state-lock
aws_s3_bucket_name: aws-demo-tfstate-bucket
