---

- name: Config ssh keys on gitlab to checkout the code
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - shared_vars.yml
    - inventories/{{ env }}/{{ env }}.yml
  roles: 
    - role: gitlab_config
  tags: ["gitlab_config"]

- name: Create s3 bucket and copy the artifacts to it
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - shared_vars.yml
    - inventories/{{ env }}/{{ env }}.yml
  roles:
    - role: s3
  tags: ["s3"]

- name: Run terraform 
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - shared_vars.yml
    - inventories/{{ env }}/{{ env }}.yml
  roles: 
    - role: tf_infra
  tags: ["tf_infra"]

...
